# Use an official Node runtime as a parent image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Clear Next.js cache
RUN rm -rf .next

# Expose the port on which the app will run
EXPOSE 3000

# Start the Next.js app in development mode with fast refresh
CMD ["npm", "run", "dev"]